### ISSUE TITLE
TypeError: data.readUIntBE is not a function

### ISSUE THREAD

**Issue by zxpectre** [cardano-foundation/ledgerjs-hw-app-cardano#37] opened 2023-07-06 22:47 UTC
Hi, we are currently hitting `TypeError: data.readUIntBE is not a function` error when calling basic methods like `ledgerAppAda.getSerial()` and `ledgerAppAda.getVersion()`, testing on a Nano S.

Aparently on this too lines:

https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/5e83052fd02c8e3bf88dbc837bb9219d80b41a40/src/utils/serialize.ts#L43

and

https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/5e83052fd02c8e3bf88dbc837bb9219d80b41a40/src/utils/serialize.ts#L57

We are using version `@cardano-foundation/ledgerjs-hw-app-cardano@6.0.0`
and because of too many dependencies to keep we are stuck in an old react-scripts 4 and node, npm versions old as well.

Is there any workaround to this posible rather than updating everything on our side please? 
Big project, small community team here!

Downgrading to  `@cardano-foundation/ledgerjs-hw-app-cardano@5.0.0` is incompatible with latest Ledger Cardano App

**Comment by refi93** [comment] 2023-07-07 08:01
the code you are referencing was present also in version 5 of this lib: https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/2b049051ffd4193ac6c713e9bfd19521ddf45525/src/utils/serialize.ts#L26 Are you sure your app would work with v5?

To pinpoint the actual issue I'd suggest trying to debug the `data` variable by adding `console.log()` into the lib (the compiled js, should be +- straightforward to get the right place, the code shouldn't be obfuscated) in `node_modules` around the place where the error happens and it should be clear from it what kind of object (apparently not a Buffer, otherwise it would have the method available) is entering the functions which should help you pinpoint the root cause on your end. I'd suspect something weird going on with the Buffer polyfill/webpack config around Buffer on the project level

**Comment by zxpectre** [comment] 2023-07-31 14:59
Hi @refi93, thanks for the answer, thought I had replied to you already, srry.
Finally downgrading to
   ` "@cardano-foundation/ledgerjs-hw-app-cardano": "^5.1.0",`
worked fine.

Still will be facing this in the future i guess, need to spend more time to deal with it.

**Comment by janmazak** [comment] 2023-08-05 16:36
I'm closing this for now since I don't see what we can do to improve the situation (we also have limited resources).

**Comment by hedi-edelbloute** [comment] 2023-12-22 09:34
Hello, it seems like we have the same problem when trying to update version from 5 to 6 on Ledger Live mobile

Weirdly no error on Ledger Live desktop, we use a require to add buffer lib so it might be related to it, I am investigating

**Comment by janmazak** [comment] 2024-01-22 12:40
Does it also occur if you use version 7? 
https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano/v/7.0.0
@hedi-edelbloute

**Comment by hedi-edelbloute** [comment] 2024-01-29 08:14
Hey @janmazak,

Thanks to the investigation of Strica, we found out that the culprit is subarray method. Buffer.subarray returns UInt8Array instead of Buffer, so data.readUIntBE is undefined. This only happens in our Ledger Live Mobile usage and not on Ledger Live Desktop.

This is not expected behavior, see :
https://github.com/feross/buffer/issues/260
https://github.com/feross/buffer/pull/263
https://github.com/feross/buffer/issues/329

Subarray usage has been introduced in v6 and is not present in v5, that's why we had no problem until now.

I don't know what's really causing the difference between those environments but maybe it's related to [int64-buffer](https://www.npmjs.com/package/int64-buffer?activeTab=readme), "It uses Buffer on Node.js and Uint8Array on modern Web browsers" as stated in the readme

Since v7 uses subarray aswell, I am confident we will have the issue.

Maybe we could go back and use slice instead of subarray ?

Have a nice day

**Comment by janmazak** [comment] 2024-02-01 14:13
@hedi-edelbloute 
Do I understand correctly that the following change would solve the problem?
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/pull/204/files
Or perhaps other instances of `subarray` should be replaced too? (I don't have anything to reproduce it with, so have to rely on your input; then I can do a new release.)

**Comment by hedi-edelbloute** [comment] 2024-02-02 09:06
Hey @janmazak that's it, other instances should be replaced too, thanks !

**Comment by janmazak** [comment] 2024-02-02 11:47
The issue should be fixed in 7.0.1:
https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano/v/7.0.1
Please try it.

**Comment by hedi-edelbloute** [comment] 2024-02-05 15:43
Hey @janmazak, thanks

Can you please provide a fix for version 6 ? We did not do the required evolutions yet to support v7

v6 is already [ready](https://github.com/LedgerHQ/ledger-live/pull/5616) but has been reverted because of this issue

**Comment by janmazak** [comment] 2024-02-07 14:56
@hedi-edelbloute 
Try: https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano/v/6.0.1
(should be v6 with `subarray` replaced with `slice`).

**Comment by hedi-edelbloute** [comment] 2024-02-16 09:26
Hi @janmazak , it fixed our issues on mobile (iOS & Android), thank you very much !

Have a nice weekend :)

**Comment by hedi-edelbloute** [comment] 2024-02-16 09:27
FYI @zxpectre

**Closed as completed** 2024-02-16 14:53 UTC
